### ISSUE TITLE
Add builds to the Github release of v115

### ISSUE THREAD

**Issue by quinton-ashley** [bsnes-emu/bsnes#22] opened 2020-05-02 13:12 UTC
Add Windows, Linux, and macOS builds to the Github release please! I don't understand why there are no builds for v115.

**Comment by aberusugi** [comment] 2020-05-10 12:31
"Builds" are typically pre-releases, in programming terms. v115 is a full release that is a starting point for bsnes moving forward on github.

**Comment by quinton-ashley** [comment] 2020-05-10 13:27
No, please add v115 release builds for bsnes.  You should make builds available on Github for every release, starting with v115.

**Comment by aberusugi** [comment] 2020-05-11 15:31
So you are referring to "binaries" not "builds". Just wanted to clarify for that reason. It's a good idea to add binaries to the releases page, yes.

**Comment by quinton-ashley** [comment] 2020-05-11 16:16
Right now I'm using the [bsnes-hd](https://github.com/DerKoun/bsnes-hd/releases) app for macOS. Maybe bsnes devs could collab with the bsnes-hd devs now that this project is on Github.

**Comment by RokkumanX** [comment] 2020-06-23 17:12
Ain't this enough?

https://cirrus-ci.com/github/bsnes-emu/bsnes/master

It's straight from the README.md

**Comment by quinton-ashley** [comment] 2020-06-23 19:07
no

**Comment by RokkumanX** [comment] 2020-06-24 16:51
> I don't understand why there are no builds for v115.

Checks https://cirrus-ci.com/github/bsnes-emu/bsnes/master
Checks https://cirrus-ci.com/build/5869603224027136

Finds Linux, FreeBSD, Windows and macOS builds

Asks if it's enough gets a **fat**

> no

Good luck mate, don't expect to find courtesy at this place.

**Comment by quinton-ashley** [comment] 2020-06-24 17:18
It's not even close to what I asked for.  Did you even read what I wrote?

**Comment by RokkumanX** [comment] 2020-06-24 17:31
You wanted builds and I pointed you to builds, I can assure you they work just as intended.
I know very well what you wrote above but don't expect things to happen that fast.

The builds I pointed you to might not be in release but again, they WORK!!!

**Comment by quinton-ashley** [comment] 2020-06-26 19:47
look at the title of this issue request please

**Comment by merwok** [comment] 2020-06-26 22:08
Maybe the request is unclear!

The github release doesn’t have binaries, but they are available on Cirrus CI: https://cirrus-ci.com/build/5044332239519744
Maybe the project maintainers don’t see a benefit in downloading files to re-upload them on github.
Even automation would take time to set up.  So you could explain why binaries downloadable from a Cirrus CI page is «not even close» to binaries downloadable from a github release page.

**Comment by kode54** [comment] 2020-06-27 04:19
He wants a link he can just stuff into his front end for distribution to users, so they’ll all just automatically grab the latest binaries from the same place. This Cirrus CI page sounds like it requires manual intervention for every build, or at the very least, page scraping that Cirrus doesn’t support. Using the api would probably require that the account doing the builds belong to him, since I don’t know of many CI services that provide an anonymous api for scraping links from just anyone’s CI page.

**Comment by quinton-ashley** [comment] 2020-06-27 21:00
^ this guy reads. I think I made the request very clear. I even linked to an github article that explains it.

**Comment by Screwtapello** [comment] 2020-10-15 13:16
Sorry it's taken a long time to respond to this issue.

The official Windows build has been added to [the v115 release page](https://github.com/bsnes-emu/bsnes/releases/tag/v115). There were no official builds for Linux or macOS, so there's nothing on the release page for those platforms.

There haven't been any official releases since bsnes became a community project, so we don't have an established process yet. For higan, we recently added release automation via GitHub Actions, which I think happens to produce releases in a format @quinton-ashley [would like](https://github.com/higan-emu/higan/releases/tag/nightly). I guess we should do that here, too. I filed #72 for that work.

Since the GitHub release of v115 now has builds, and since future releases should be covered by #72, I don't think there's anything more to be done here, so I'll close this issue.

**Closed by Screwtapello** 2020-10-15 13:16 UTC

**Comment by quinton-ashley** [comment] 2020-10-18 01:53
Thank you! Yes keeping the file names the same would be ideal. Perhaps now that this is a community project there could be collaboration with [bsnes-hd](https://github.com/DerKoun/bsnes-hd/releases) on official macOS and Linux builds?

**Comment by jchv** [comment] 2020-10-18 17:35
We should have no problem providing Linux and mac builds for bsnes; we do so for Higan right now. Check PR #74 - it has links to releases created by the GitHub Actions CI. Let me know if those releases work for you.

**Comment by quinton-ashley** [comment] 2020-10-18 23:43
That looks great!
