### ISSUE TITLE
Request to add an input display

### ISSUE THREAD

**Issue by uhyeahright** [bsnes-emu/bsnes#310] opened 2024-02-08 23:06 UTC
I am requesting that an input display to be added.

**Comment by Screwtapello** [comment] 2024-02-09 02:23
Duplicate of #259, I think. Please re-open if I've misunderstood.

**Closed by Screwtapello** 2024-02-09 02:23 UTC

**Comment by Kawa-oneechan** [comment] 2024-02-09 22:53
I think this could just as well mean having buttons in a corner that reflect the current inputs, like in some TAS videos.
